# Generated by Django 5.0.6 on 2024-06-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_course_teacher'),
        ('student', '0004_alter_check_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
