# Generated by Django 5.0.6 on 2024-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='author.jpg', upload_to=''),
        ),
    ]
