# Generated by Django 5.0.6 on 2024-05-28 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname_st', models.CharField(max_length=255)),
                ('mail_st', models.CharField(max_length=255)),
                ('birthday_st', models.DateField()),
                ('datecreated_st', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname_tr', models.CharField(max_length=255)),
                ('mail_tr', models.CharField(max_length=255)),
                ('birthday_tr', models.DateField()),
                ('datecreated_tr', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=255)),
                ('price_course', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(to='app.student')),
                ('teachers', models.ManyToManyField(to='app.teacher')),
            ],
        ),
    ]
