# Generated by Django 5.0.6 on 2024-06-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_comment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
