# Generated by Django 5.0.6 on 2024-06-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_course_teachers_remove_student_courses_and_more'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('rating', models.FloatField(default=5.0)),
                ('student', models.ManyToManyField(to='student.student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
