# Generated by Django 5.0.6 on 2024-06-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
