# Generated by Django 5.0.6 on 2024-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_course_teacher_course_teacher'),
        ('teacher', '0002_teacher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='teacher.teacher'),
        ),
    ]
