# Generated by Django 5.0.6 on 2024-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
